### PR TITLE
Add Scala version chooser component... thing.

### PR DESCRIPTION
**Pull request by megri**
This adds a rather ugly radio button component for picking a Scala Version to the left of the page. I've tried to make it behave like the other FormField components.

The chosen version affects the generated .scalafmt.conf and build.sbt files.

### CODE REVIEW

**Comment by kitlangton** [comment]
Awesome! I think this has a conflict due to the other PR. But happy to merge when it's resolved 🙇 

Thanks so much!

**Comment by megri** [comment]
> Awesome! I think this has a conflict due to the other PR. But happy to merge when it's resolved 🙇
> 
> Thanks so much!

Resolved :)

I threw in some updates to .gitignore as I had to add them to do the rebase. I could drop them from this PR if so desired, but they should be benign.

**Comment by kitlangton** [comment]
Woo! Good to go? :D Happy to merge if you're ready

**Comment by megri** [comment]
I think it's ready. I messed up the first rebase and didn't notice, but it seems to be ok now :)

**Pull request merged**
